name: Epic
description: Create a high-level container issue (Epic)
title: "[EPIC] "
labels: ["EPIC"]
assignees: []   # Epics should never be assigned
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: High-level description of the epic (scope and purpose)
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: Subfunctions (checklist)
      description: List the main subfunctions that belong to this Epic
      placeholder: |
        - [ ] Subfunction A
        - [ ] Subfunction B

  - type: textarea
    id: substories
    attributes:
      label: User Stories (Sub-issues)
      description: "Add each User Story as a checkbox with a #link to enable native progress"
      placeholder: |
        - [ ] #<user-story-id>
    validations:
      required: true

  - type: textarea
    id: linked-stories-deprecated
    attributes:
      label: "Linked User Stories (deprecated — use tasklist above)"
      description: "Backward compatibility only. Prefer the tasklist above."
      placeholder: |
        - [ ] #123
        - [ ] #124
    validations:
      required: false
