name: Task
description: Create a technical sub-task linked to a User Story
title: "Task: "
labels: ["TASK"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What should be implemented or fixed?
      placeholder: "Implement POST /api/auth/register ..."
    validations:
      required: true

  - type: textarea
    id: tech-notes
    attributes:
      label: "Technical Notes (optional)"
      description: "Architecture decisions, libraries, or important implementation details"
      placeholder: "- Use ASP.NET Identity\n- Hash password with PasswordHasher"
    validations:
      required: false

  - type: textarea
    id: out-of-scope
    attributes:
      label: "Out of Scope (optional)"
      description: "What is explicitly not included in this Task"
      placeholder: "- Not handling social login in this Task"
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List the conditions for this Task to be considered complete.
      placeholder: |
        * Build green (`dotnet build -c Release`)
        * Tests green (`dotnet test -c Release --no-build`)
        * API contract updated (Swagger)
    validations:
      required: true
