name: User Story
description: Create an assignable User Story
title: "User Story: "
labels: ["USER STORY"]
body:
  - type: input
    id: role
    attributes:
      label: As a
      placeholder: Student / FreeStudent / Mentor / Admin / Guest
    validations:
      required: true

  - type: input
    id: goal
    attributes:
      label: I want
      placeholder: Briefly describe what the user wants to achieve
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: So that
      description: Explain why this is valuable to the user (business value / problem solved)
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List the conditions when this story is considered done
      placeholder: |
        - [ ] Condition 1
        - [ ] Condition 2
    validations:
      required: true

  - type: textarea
    id: tasks-subissues
    attributes:
      label: Tasks (Sub-issues)
      description: "Add every Task as a checkbox `- [ ] #<task-id>` to enable native progress"
      placeholder: |
        - [ ] #<task-id>
    validations:
      required: true

  - type: input
    id: epic-parent
    attributes:
      label: Epic (optional)
      description: "If applicable, link the parent Epic by number (e.g., #1). Note: Epic should also include this US in its tasklist."
      placeholder: "#<epic-id>"
    validations:
      required: false

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes (optional)
      description: Add implementation details, APIs, DB tables, etc.
