<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>Api.UnitTests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="AutoFixture.AutoMoq" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
	<PackageReference Include="coverlet.collector" />
    <PackageReference Include="Moq" />
	<PackageReference Include="FluentAssertions" />
	<PackageReference Include="FluentAssertions.Json" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	<PackageReference Include="Testcontainers" />
	<PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
	<PackageReference Include="xunit.runner.visualstudio">
		<PrivateAssets>all</PrivateAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\backend\Api\Api.csproj" />
    <ProjectReference Include="..\..\src\backend\Application\Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
	<ItemGroup>
		<!--Replace to CopyToOutputDirectory=PreserveNewest-->
		<None Include="TestcontainerInitDb\**\*" CopyToOutputDirectory="Always" />
	</ItemGroup>
</Project>
