name: workshopcode

services:
  db:
    image: postgres:16
    ports:
      - "${POSTGRES_PORT_EXT}:${POSTGRES_PORT_INT}"
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB: ${APP_DB}
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [internal]

  api:
    build:
      context: ..
      dockerfile: docker/Api.Dockerfile
      args:
        API_PORT_INT: ${HTTP_PORT_INT}
    env_file:
      - .env
    volumes:
      - ./dpkeys:/keys
    environment:
      # перекрывает appsettings.Development.json:
      ConnectionStrings__Default: "Host=db;Port=${POSTGRES_PORT_INT};Database=${POSTGRES_DB};Username=${APP_USER};Password=${APP_PASSWORD};Pooling=true"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_DataProtection__ApplicationName: WorkshopCode.Dev
      DataProtection__Path: /keys
      ASPNETCORE_HTTP_PORTS: "${HTTP_PORT_INT}"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${HTTP_PORT_EXT}:${HTTP_PORT_INT}"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${HTTP_PORT_INT}/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 12
    networks: [internal]

networks:
  internal:

volumes:
  pgdata:
