<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<RootNamespace>Api</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>035fdf77-3ec2-4181-9370-8dd375dfd963</UserSecretsId>
  </PropertyGroup>
	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<!-- чтобы не ругался на отсутствующие комментарии -->
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="SeaWind.Api.Tests" />
	</ItemGroup>
	<!--Это не логическая связь Api c Application и Infrastructure, а технологическая для запуска DI-->
	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
		<ProjectReference Include="..\Infrastructure.Postgres\Infrastructure.Postgres.csproj" />
	</ItemGroup>
</Project>
