<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<RootNamespace>Api</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="SeaWind.Api.Tests" />
	</ItemGroup>
</Project>
